### ISSUE TITLE
Issue when cleaning Temporary Files

### ISSUE THREAD

**Issue by streetwolf** [builtbybel/CleanmgrPlus#10]
Every time I use Cleanmgr+ to clean my Temporary Files it creates an empty folder under my C:\Users folder.  My user account is called 'Gary Shapiro'.  The new empty folder is called 'Gary'. Obviously there is a glitch somewhere when cleaning the Temp Files.

**Comment by streetwolf** [comment]
Anyone there?

**Comment by Belim** [comment]
Ive tried to recreate this problem and so far unsuccessfully :worried:

**Comment by streetwolf** [comment]
I no longer have this issue.  Perhaps it is because I am now running v1.34.1074.  Isn't this a beta version?

I found another issue.  Clearing Recent Documents doesn't get rid of the 322  files contained within the folder.  Take a look:

[Recent1.txt](https://github.com/builtbybel/CleanmgrPlus/files/4873822/Recent1.txt)
[Recent2.txt](https://github.com/builtbybel/CleanmgrPlus/files/4873823/Recent2.txt)
