### ISSUE TITLE
Cleanmgr+ less than MS Cleanmgr?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [builtbybel/CleanmgrPlus#13]
Hi.
Cleanmgr+ with shown 1.15GB has less than MS Cleanmgr with 3.9GB.
But in your Cleanmgr+ i can not click "Windows Komponentenstore" what could explain the difference?
What does this mean? :)

**Comment by Belim** [comment]
Hi,
did you start Cleanmgr+ with admin rights? It could be the Windows update cleanup

The results between the cleanmgr.exe and Cleanmgr+ will never match 1:1  as  Cleanmgr+ calculates slightly differently and cleans up many times more thoroughly.

You could for example test our second cleanmgr.exe replica, called [Burnbytes](https://github.com/builtbybel/burnbytes). Here you will see that it matches 1:1 with the results of cleanmgr.exe

**Comment by Clemens-Ratte-Polle** [comment]
OK, Cleanmgr+ with admin rights 1,32GB
In Windows 10 Cleanmgr i also click "Systemdateien bereinigen" (Clean System Files?), this could make da difference?
