### ISSUE TITLE
Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by A9G-Data-Droid** [builtbybel/CleanmgrPlus#15]
I just downloaded Cleanmgr+ v1.34.1080 and Windows Defender flagged your ZIP file as Trojan:Win32/Azden.A!cl which is rated as threat level "Severe". This needs to be resolved because users should not be told to ignore/bypass/allow any threat labeled "Severe".

![image](https://user-images.githubusercontent.com/26984068/90720420-57c30c80-e26b-11ea-89d1-b83f313c507b.png)

VirusTotal says "No engines detected this file" so it might be a false positive but if that's the case it needs to be addressed from the Microsoft end.

Is anyone else seeing this?

**Comment by Aeroman** [comment]
Hey Thank you for pointing out! Have just checked the installed version (1.34) and Virustotal unfortunately raises alarm and 1 detection as Malware?! Also not so safe & serious this application?
![a2020-08-20 202434]

here to be seen on the following screenie:

(https://user-images.githubusercontent.com/7405364/90810520-64a33700-e323-11ea-947a-3cec82650471.jpg)

**Comment by A9G-Data-Droid** [comment]
Yeah, malware gets injected in to legitimate occasionally. It happened to CCleaner. 

I opened a ticket with Microsoft about it and their analysis team has removed the detection from their signature database. So I am going to close this as false positive. If you update defender you won't see this anymore and we think the release is safe to use now.

**Comment by Aeroman** [comment]
injected by whom? I have downloaded it from Github
My workstation is always secured (virus & Security programs and firewalls) 
But they haven't sounded any alarms strangely, this only reports VirusTotal. :/
I had several times checked my System there was no detections.

**Comment by A9G-Data-Droid** [comment]
I'm not sure if you read my full message. This was a false positive. It's no longer detected by Microsoft because I opened a ticket with their malware team.

If you want to know about CCleaner you can read this article: https://time.com/4946576/ccleaner-malware-hack/
