### ISSUE TITLE
Script fail

### ISSUE THREAD

**Issue by killo3967** [builtbybel/CleanmgrPlus#17]
Hi.

I have tried the following script but could not get it to work. Could you tell me why?

[Info]
Title=Windows Temp Files ALL USERS
Description= Elimina los ficheros temporales de todos los usuarios
Author=Tomas Platero

[Files]
Task1=Exec|for /F "delims=" %i in ('dir C:\Users /ad /b ^| findstr /V /I "User" ^| findstr /V /I "default" ^| findstr /V /I "public" ^| findstr /V /I ".NET"' ^| findstr /V /I "MSSQL"') do del /F /Q /S "C:\Users\%i\AppData\Local\Temp\*.*"|SHOWCLI

**Comment by Belim** [comment]
Your script is only partially recognized because Multiline is not easily supported by Cleanmgr+. 
I would rather put it into a batch and link to it in Cleanmgr+.
